/**
 * File: audio.c
 * Description: Cart-shared audio buffer producer (single-channel
 *              YM2149 ch A 4-bit DAC).
 *
 * The m68k Timer-B IRQ at ~6.27 kHz reads one byte per fire from
 * the 256-byte cart buffer at CART_AUDIO_BUFFER_OFFSET. Each byte
 * is a YM volume nibble (0..15) in its low 4 bits.
 *
 * Source signal: a pre-converted jingle (audio_sample_data[] in
 * audio_sample.h, generated by tools/wav_to_ym4.py from
 * connected.wav at 6269 Hz / single-a mode). Each entry is already
 * a YM ch A volume nibble, so no runtime LUT lookup is needed.
 * Looped continuously.
 *
 * audio_render_frame() paces the cart-buffer fills via time_us_32
 * to roughly match the m68k's consumption rate.
 */

#include "audio.h"

#include <stdint.h>

#include "audio_sample.h"
#include "cart_shared.h"
#include "constants.h"
#include "debug.h"
#include "pico/stdlib.h"
#include "pico/time.h"

static uint8_t *s_audio_buf;
static uint32_t s_sample_pos = 0;

/* Per-frame fill cadence. Refill every ~20 ms (one PAL VBL) so the
 * RP keeps pace with the m68k's Timer-B reads without burning more
 * main-loop cycles than necessary. */
#define AUDIO_FRAME_PERIOD_US 20000u
static uint32_t s_last_frame_us = 0;

/* Dual-channel Ghostbusters-LUT jingle: 2 bytes per sample (vA, vB).
 *   Timer-B = 5,585.5 Hz, PAL VBL = 49.92 Hz -> 111.71 samples/VBL
 *   = 223.43 bytes/VBL.
 * We advance the source by 224 bytes (= 112 samples) each refill;
 * 0.26% pitch drift, inaudible. AUDIO_FILL_COUNT covers the full
 * 1024-byte buffer so the m68k always sees fresh data across the
 * ~800 bytes of headroom. */
#define AUDIO_BYTES_PER_VBL    224u
#define AUDIO_FILL_COUNT       1024u

void audio_init(void) {
  uint8_t *base = (uint8_t *)&__rom_in_ram_start__;
  s_audio_buf = base + CART_AUDIO_BUFFER_OFFSET;

  s_sample_pos = 0;
  s_last_frame_us = 0;

  /* ERASE_FIRMWARE_IN_RAM at emul_start already zeroed the cart
   * buffer (= silence on YM). The jingle starts when the first
   * audio_render_frame call fills the buffer. */

  DPRINTF(
      "audio_init: single-ch A YM DAC, jingle %u samples @ %u Hz "
      "(%u ms loop), cart buffer %u bytes\n",
      (unsigned)audio_sample_count,
      (unsigned)AUDIO_SAMPLE_RATE_HZ,
      (unsigned)((audio_sample_count * 1000u) / AUDIO_SAMPLE_RATE_HZ),
      (unsigned)CART_AUDIO_BUFFER_SIZE);
}

void audio_render_frame(void) {
  /* Pace to ~50 Hz. The m68k's userfw_vbl handler resets A0 to the
   * cart buffer base at every VBL, so each VBL the m68k reads
   * buffer[0..~125]. We fill buffer[0..AUDIO_FILL_COUNT-1] each
   * refill with the next AUDIO_FILL_COUNT samples of the looped
   * jingle, and advance the source by AUDIO_SAMPLES_PER_VBL (=126)
   * each refill to match the m68k's per-VBL consumption rate. */
  uint32_t now_us = time_us_32();
  if (s_last_frame_us != 0 &&
      (now_us - s_last_frame_us) < AUDIO_FRAME_PERIOD_US) {
    return;
  }
  s_last_frame_us = now_us;

  uint32_t src = s_sample_pos;
  for (uint32_t i = 0; i < AUDIO_FILL_COUNT; i++) {
    s_audio_buf[i] = audio_sample_data[src];
    src++;
    if (src >= audio_sample_count) {
      src = 0;  /* loop the jingle */
    }
  }
  /* Source advances by BYTES_PER_VBL (not FILL_COUNT) so the jingle
   * plays at its natural rate -- the extra bytes of fill are just
   * a safety margin for Timer-B / VBL drift. */
  src = s_sample_pos + AUDIO_BYTES_PER_VBL;
  if (src >= audio_sample_count) {
    src -= audio_sample_count;
  }
  s_sample_pos = src;
}
