/* Generated by tools/png_to_bitmap.py from crosshair.png: do not edit. */
#ifndef CROSSHAIR_BITMAP_H
#define CROSSHAIR_BITMAP_H

#include <stdint.h>

#include "fb_blit.h"

#define CROSSHAIR_W 16
#define CROSSHAIR_H 16
#define CROSSHAIR_KEY 15

/* The PNG's palette, as ST colour words (palette_set()). */
static const uint16_t crosshair_palette[16] = {
    0x000, 0x002, 0x013, 0x124, 0x223, 0x334, 0x556, 0x777, 0x760, 0x630, 0x601, 0x300, 0x066, 0x034, 0x262, 0x707,
};

static const uint8_t crosshair_pixels[256] = {
    15, 15, 15, 15, 15, 15,  0,  0,  0,  0, 15, 15, 15, 15, 15, 15,
    15, 15, 15, 15,  0,  0,  7,  7,  7,  7,  0,  0, 15, 15, 15, 15,
    15, 15, 15,  0,  7,  7,  0,  0,  0,  0,  7,  7,  0, 15, 15, 15,
    15, 15,  0,  7,  0,  0, 15, 15, 15, 15,  0,  0,  7,  0, 15, 15,
    15,  0,  7,  0, 15, 15, 15, 15, 15, 15, 15, 15,  0,  7,  0, 15,
    15,  0,  7,  0, 15, 15, 15, 15, 15, 15, 15, 15,  0,  7,  0, 15,
     0,  7,  0, 15, 15, 15, 15,  0,  0, 15, 15, 15, 15,  0,  7,  0,
     0,  7,  0, 15, 15, 15,  0,  7,  7,  0, 15, 15, 15,  0,  7,  0,
     0,  7,  0, 15, 15, 15,  0,  7,  7,  0, 15, 15, 15,  0,  7,  0,
     0,  7,  0, 15, 15, 15, 15,  0,  0, 15, 15, 15, 15,  0,  7,  0,
    15,  0,  7,  0, 15, 15, 15, 15, 15, 15, 15, 15,  0,  7,  0, 15,
    15,  0,  7,  0, 15, 15, 15, 15, 15, 15, 15, 15,  0,  7,  0, 15,
    15, 15,  0,  7,  0,  0, 15, 15, 15, 15,  0,  0,  7,  0, 15, 15,
    15, 15, 15,  0,  7,  7,  0,  0,  0,  0,  7,  7,  0, 15, 15, 15,
    15, 15, 15, 15,  0,  0,  7,  7,  7,  7,  0,  0, 15, 15, 15, 15,
    15, 15, 15, 15, 15, 15,  0,  0,  0,  0, 15, 15, 15, 15, 15, 15,
};

static const struct FB_BITMAP crosshair = {16, 16, crosshair_pixels};

#endif /* CROSSHAIR_BITMAP_H */
