/* Generated by tools/png_to_bitmap.py from bolt.png: do not edit. */
#ifndef BOLT_BITMAP_H
#define BOLT_BITMAP_H

#include <stdint.h>

#include "fb_blit.h"

#define BOLT_W 8
#define BOLT_H 8
#define BOLT_KEY 15

/* The PNG's palette, as ST colour words (palette_set()). */
static const uint16_t bolt_palette[16] = {
    0x000, 0x002, 0x013, 0x124, 0x223, 0x334, 0x556, 0x777, 0x760, 0x630, 0x601, 0x300, 0x066, 0x034, 0x262, 0x707,
};

static const uint8_t bolt_pixels[64] = {
    15, 15,  0,  0,  0,  0, 15, 15,
    15,  0,  7,  7,  8,  8,  0, 15,
     0,  7,  7,  8,  8,  8,  9,  0,
     0,  7,  8,  8,  8,  8,  9,  0,
     0,  8,  8,  8,  8,  9,  9,  0,
     0,  8,  8,  8,  9,  9,  9,  0,
    15,  0,  9,  9,  9,  9,  0, 15,
    15, 15,  0,  0,  0,  0, 15, 15,
};

static const struct FB_BITMAP bolt = {8, 8, bolt_pixels};

#endif /* BOLT_BITMAP_H */
